# .github/workflows/release.yml
name: Release

on:
  push:
    branches:
      - my-temp-release-check

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: ChorusOne/semver-release-action@workaround-for-org-errors
        with:
          release_branch: my-temp-release-check
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
